build-package new release: dom 30 mar 2025 14:05:21 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/pkgbuild/pkgbuild.install b/pkgbuild/pkgbuild.install
--- a/pkgbuild/pkgbuild.install
+++ b/pkgbuild/pkgbuild.install
@@ -29,6 +29,7 @@ export DOTPREFIX="  ${black}::${reset} "
 export bold="\033[1m"
 export reset="\033[0m"
 declare IS_UPGRADE=false
+declare IS_DBLOCK=false
 declare DM='lightdm'
 declare WM='bigcontrolcenter-base'
 declare pkgname="${WM}"
@@ -64,8 +65,10 @@ sh_load_optdepends() {
 }
 
 sh_restoring_lock() {
-	msg "Restauring pacman lock: /var/lib/pacman/db.lck"
-	touch /var/lib/pacman/db.lck &>/dev/null
+	if $IS_DBLOCK; then
+		msg "Restauring pacman lock: /var/lib/pacman/db.lck"
+		touch /var/lib/pacman/db.lck &>/dev/null
+	fi
 }
 
 sh_check_package_exist() {
@@ -137,7 +140,6 @@ sh_copy_user_etc_usr_opt_files() {
 post_install() {
 	msg "Initializing system installation and configuration..."
 
-	sh_copy_user_etc_usr_opt_files
 	sh_load_optdepends
 
 	[[ -e /etc/environment ]] && source /etc/environment
@@ -150,6 +152,7 @@ post_install() {
 	fi
 
 	if [[ -f /var/lib/pacman/db.lck ]]; then
+		IS_DBLOCK=true
 		msg "Removing pacman lock: /var/lib/pacman/db.lck"
 		rm -f /var/lib/pacman/db.lck &>/dev/null
 	fi
@@ -159,14 +162,21 @@ post_install() {
 	}
 
 	install_packages() {
-		pacman -S --quiet --noconfirm --needed --overwrite \* "$@" &>/dev/null
+		# Captura o erro do pacman
+		if ! pacman -S --quiet --noconfirm --needed --overwrite \* "$@" >/tmp/${pkgname}-pacman_output_log 2>/tmp/${pkgname}-pacman_error_log; then
+			die "$(</tmp/${pkgname}-pacman_error_log)"
+		fi
+		# Se não houver erro (ou erro de já estar instalado/atualizado)
+		rm /tmp/${pkgname}-pacman_error_log &>/dev/null
+		rm /tmp/${pkgname}-pacman_output_log &>/dev/null
+		return 0
 	}
 
-	msg "Please wait, synchronizing databases..."
-	synchronizing_database
+	#	msg "Please wait, synchronizing databases..."
+	#	synchronizing_database
 
-	msg "Checking for the existence of packages..."
-	sh_check_package_exist
+	#	msg "Checking for the existence of packages..."
+	#	sh_check_package_exist
 
 	msg "Installing optdepends packages: ${OPTDEPENDS[*]}"
 	install_packages "${OPTDEPENDS[@]}"
@@ -193,6 +203,8 @@ post_install() {
 			fi
 		fi
 	done
+
+	sh_copy_user_etc_usr_opt_files
 
 	# Restauring pacman lock: /var/lib/pacman/db.lck
 	sh_restoring_lock
